version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    volumes:
      - "./ui/nginx.conf:/etc/nginx/nginx.conf"
  
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy/conf.d:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
