version: '3'
services:
  typingwars:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: typingwars
    ports:
      - "8080:8080"
  
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy/conf.d:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
