// Code generated by protoc-gen-go. DO NOT EDIT.
// source: typingwars.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Content:
	//	*Message_PlayerJoined
	Content              isMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b666822ed8f2be0, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Content interface {
	isMessage_Content()
}

type Message_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,1,opt,name=playerJoined,proto3,oneof"`
}

func (*Message_PlayerJoined) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetPlayerJoined() *PlayerJoined {
	if x, ok := m.GetContent().(*Message_PlayerJoined); ok {
		return x.PlayerJoined
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_PlayerJoined)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_PlayerJoined:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerJoined); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Content has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // content.playerJoined
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerJoined)
		err := b.DecodeMessage(msg)
		m.Content = &Message_PlayerJoined{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_PlayerJoined:
		s := proto.Size(x.PlayerJoined)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PlayerJoined struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoined) Reset()         { *m = PlayerJoined{} }
func (m *PlayerJoined) String() string { return proto.CompactTextString(m) }
func (*PlayerJoined) ProtoMessage()    {}
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b666822ed8f2be0, []int{1}
}

func (m *PlayerJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoined.Unmarshal(m, b)
}
func (m *PlayerJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoined.Marshal(b, m, deterministic)
}
func (m *PlayerJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoined.Merge(m, src)
}
func (m *PlayerJoined) XXX_Size() int {
	return xxx_messageInfo_PlayerJoined.Size(m)
}
func (m *PlayerJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoined.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoined proto.InternalMessageInfo

func (m *PlayerJoined) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerJoined) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "typingwars.Message")
	proto.RegisterType((*PlayerJoined)(nil), "typingwars.PlayerJoined")
}

func init() { proto.RegisterFile("typingwars.proto", fileDescriptor_1b666822ed8f2be0) }

var fileDescriptor_1b666822ed8f2be0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xa9, 0x2c, 0xc8,
	0xcc, 0x4b, 0x2f, 0x4f, 0x2c, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x85, 0x70, 0xb1, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xd9, 0x71, 0xf1, 0x14,
	0xe4, 0x24, 0x56, 0xa6, 0x16, 0x79, 0xe5, 0x67, 0xe6, 0xa5, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x1b, 0x49, 0xe8, 0x21, 0xe9, 0x0f, 0x40, 0x92, 0xf7, 0x60, 0x08, 0x42, 0x51, 0xef, 0xc4,
	0xc9, 0xc5, 0x9e, 0x9c, 0x9f, 0x57, 0x92, 0x9a, 0x57, 0xa2, 0x64, 0xc5, 0xc5, 0x83, 0xac, 0x54,
	0x88, 0x8f, 0x8b, 0x29, 0x13, 0x62, 0x20, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x14, 0x17, 0x47,
	0x69, 0x71, 0x6a, 0x51, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x14, 0xce, 0x77, 0x62, 0x89,
	0x62, 0x2a, 0x48, 0x4a, 0x62, 0x03, 0x3b, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x56, 0xe8,
	0x31, 0x9a, 0xbe, 0x00, 0x00, 0x00,
}
